# EnigmaBOT

You've been newly recruited into a secret government agency in a post-apocalyptic world ravaged by a devastating zombie outbreak. Your agency has intercepted an `encrypted transmission` from a rival faction suspected of harboring critical information about the origins of the virus and potential treatments.
<br /> <br />
However, the encryption used in this transmission is unlike anything your group has encountered before. It appears to be based on an intricate system of linguistic patterns and statistical anomalies, rendering traditional decryption methods useless.
<br /> <br />
Fortunately, your group has recently acquired a secret technology `EnigmaBOT`, a pre-trained language model that has been exposed to a vast corpus of text spanning medical research, scientific literature, and classified government documents related to viral outbreaks and bioweapons.

Your mission is to leverage this pre-trained model's capabilities to decipher the encrypted transmission and uncover any insights or clues that could lead to a cure or a better understanding of the virus.

- Encrypted transmission: `9Zx4Qp 8Yw3Po 7Xv2On 6Wu1Nm 5Vt0Ml 4Us9Lk 3Tr8Kj 2Sq7Ji`

## Import necessary libraries

If you have any missing libraries, you can install them by running the following command in your terminal or command prompt (Make sure you have pip installed): `pip install library1 library2`

In [ ]:
import torch
from torch import nn

In [ ]:
import warnings
warnings.filterwarnings('ignore')

## RNN model class

The following code should allow you to load the enigmabot model

In [ ]:
class ENIGMABOT(nn.Module):
    def __init__(self):
        super(ENIGMABOT, self).__init__()

        self.embedding = nn.Embedding(256, 32)
        self.lstm = nn.LSTM(32,128, 2, batch_first=True, dropout=.1)
        self.fc = nn.Sequential(
            nn.Linear(128, 128),
            nn.LayerNorm(128),
            nn.ELU(),
            nn.Linear(128, 256)
        )

    def forward(self, input):
        embedded = self.embedding(input)
        output = self.lstm(embedded)[0][:,-1,:]
        prediction = self.fc(output)
        return prediction

In [ ]:
model = ENIGMABOT()
model.load_state_dict(torch.load("enigmabot_model.pt"))

<All keys matched successfully>

In [ ]:
model

ENIGMABOT(
  (embedding): Embedding(256, 32)
  (lstm): LSTM(32, 128, num_layers=2, batch_first=True, dropout=0.1)
  (fc): Sequential(
    (0): Linear(in_features=128, out_features=128, bias=True)
    (1): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (2): ELU(alpha=1.0)
    (3): Linear(in_features=128, out_features=256, bias=True)
  )
)

## Solution

## some explination :
### since we have language model so we should do these steps :


1.   convert our string to numbers(all we know ai understand just numbers 🔢
2.   turn them to tensor
3.   the output will be the input until we get all the flag



In [ ]:
input_text = "hello"

# Convert input text to ASCII representation
ascii_input = [ord(char) for char in input_text]
input_tensor = torch.tensor(ascii_input)

tensor([104, 101, 108, 108, 111])

In [ ]:
input_text = "9Zx4Qp 8Yw3Po 7Xv2On 6Wu1Nm 5Vt0Ml 4Us9Lk 3Tr8Kj 2Sq7Ji"
ascii_values = [ord(char) for char in input_text]
input_tensor = torch.tensor([ascii_values])


with torch.no_grad():
    model.eval()
    output = model(input_tensor)


print("Output shape:", output.shape)

Output shape: torch.Size([1, 256])


In [ ]:
output

tensor([[-3.9330, -4.1055, -3.0672, -3.0536, -3.4939, -3.6775, -3.3135, -3.4741,
         -3.6486, -3.2803, -3.7822, -3.7483, -3.2000, -3.6906, -3.6204, -3.1931,
         -3.4448, -3.3458, -4.2216, -3.1146, -3.0065, -4.6436, -3.0217, -2.5009,
         -3.3505, -3.6892, -3.0328, -3.9642, -3.8289, -3.8827, -3.6232, -3.5078,
          1.7441, -3.7820, -3.2698, -4.7138, -3.6657, -4.2407, -3.6793, -3.3008,
         -3.7128, -2.7638, -3.2557, -4.3565, -4.3096, -3.3595, -0.5079, -3.8348,
         -4.1795, -3.0361, -4.0217, -3.2034, -2.5955, -3.6686, -4.7298, -3.1528,
         -3.8224, -3.7086, 11.7517, -4.0357, -4.4856, -3.5811, -3.5493, -3.8510,
         -3.4796, -1.6326,  1.1275, -3.5197,  0.8826, -6.9957, -3.8773, -3.8053,
          0.4453, -0.6176, -3.6198, -2.8796, -4.0380, -1.1918,  1.3303,  0.9725,
         -1.1172, -3.4511, -0.8516, -0.0567, -1.9776, -4.7852, -3.3983, -3.7372,
         -3.3309, -1.0768, -2.0373, -4.0039, -3.4072, -4.5036, -3.9030, -3.7521,
         -3.9462, -2.4730, -

In [ ]:
m = np.argmax(output, axis=1)

In [ ]:
m

tensor([58])

In [ ]:
chr(58)

':'

In [ ]:
input_text = ": in"
flag = ""
i = 0
for i in range(90) :
  ascii_values = [ord(char) for char in input_text]
  input_tensor = torch.tensor([ascii_values])


  # Pass the input through the model
  with torch.no_grad():
      model.eval()
      output = model(input_tensor)
  input_text = input_text + chr(np.argmax(output, axis=1)[0].numpy())

##Result 😇

In [ ]:
print(input_text)

: ingeneer{IMMUNEBOOSTERSREADY.PATHOGENMUTATIONSTABILIZED.DISTRIBUTIONPLAN}}}{IMUTABILIZED.DIS
